export function createInitialPhysicsState() {
  return {
    active: false,
    mode: "idle",
    targetType: null,
    target: null,
    equipment: null,
    tension: 0,
    lastTension: 0,
    lineLength: 0,
    straightLineDistance: 0,
    slack: 0,
    lineTaut: false,
    lineCondition: 100,
    breakThreshold: 0,
    spoolRemaining: 0,
    spoolCapacity: 0,
    snapTautImpulse: 0,
    hotZoneTimer: 0,
    rpm: 0,
    avatarPullForce: 0,
    dragThresholdMin: 0,
    dragThresholdMax: 0,
    dragThresholdCurrent: 0,
    dragQuickReleaseActive: false,
    reactiveDrag: 0,
    playerLineForce: 0,
    totalPlayerResistance: 0,
    linePayout: 0,
    objectVelocity: 0,
    radialVelocity: 0,
    objectApproachRate: 0,
    slackChangeRate: 0,
    playerRecoveryVelocity: 0,
    objectState: "static",
    staticBreakTimer: 0,
    distanceToShore: 0,
    forces: {
      avatarPull: 0,
      reactiveDrag: 0,
      playerLineForce: 0,
      totalPlayerResistance: 0,
      swim: 0,
      velocityDrag: 0,
      external: 0,
      friction: 0,
      totalObject: 0,
      objectLineForce: 0,
      net: 0,
      playerForceVector: { x: 0, y: 0 },
    },
    slip: {
      accumulation: 0,
      limit: 0,
      percent: 0,
    },
    fishStatus: {
      energy: 0,
      panic: 0,
      state: null,
      fightPhase: null,
    },
    waitState: null,
    events: {},
    environment: {
      current: { strength: 0, direction: { x: 1, y: 0 } },
    },
  };
}
